name: agentbuddys
description: CRM App for Insurance agents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.7
  intl: ^0.18.1
  share_plus: ^7.2.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.0.4
  speech_to_text: ^7.0.0
  file_picker: ^10.1.9
  razorpay_flutter: ^1.3.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/agentbuddys_logo.png
    - assets/default_avatar.png

dependency_overrides:
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0



