name: agentbuddys
description: CRM App for Insurance agents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Charts & visuals
  pie_chart: ^5.3.2
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2

  # Supabase backend
  supabase_flutter: ^1.10.25

  # Calendar & Dates
  intl: ^0.20.2   # ✅ Updated to match table_calendar
  table_calendar: ^3.2.0   # ✅ Use the latest compatible version

  # PDFs & Printing
  pdf: ^3.10.4
  printing: ^5.11.0

  # File & sharing
  url_launcher: ^6.1.12
  share_plus: ^7.2.2
  file_picker: ^10.1.9
  path_provider: ^2.1.2



  # Notifications & timezone
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4  # ✅ Upgraded for compatibility

  # Media & speech
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.0.4
  speech_to_text: ^7.0.0

  # Permissions & contacts
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.9+2  # ✅ Use the stable latest version

  # Payments
  razorpay_flutter: ^1.3.5

  # Animations
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_contacts: ^1.1.7
  permission_handler: ^11.3.1
  clipboard: ^0.1.3

  open_filex: ^4.3.2




flutter:
  uses-material-design: true
  assets:
    - assets/agentbuddys_logo.png
    - assets/default_avatar.png
    - assets/lottie/cashflow_hero.json
    - assets/lottie/success_tick.json
    - assets/lottie/advisor.json

dependency_overrides:
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0

