import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

class ServiceLogPdfHelper {
  /// Generate a PDF with client name, month, and list of logs
  static Future<Uint8List> generatePdf({
    required String clientName,
    required List<Map<String, dynamic>> logs,
    required String month,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => [
          pw.Text(
            "$clientName - Service Log",
            style: pw.TextStyle(
              fontSize: 22,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            "Month: $month",
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.normal,
            ),
          ),
          pw.SizedBox(height: 16),
          pw.Table.fromTextArray(
            border: pw.TableBorder.all(width: 0.5, color: PdfColors.grey),
            cellPadding: const pw.EdgeInsets.all(5),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColors.blueGrey,
            ),
            headers: ['Date', 'Service Type', 'Details', 'Channel'],
            data: logs.map((log) {
              return [
                DateFormat('dd MMM yyyy, hh:mm a')
                    .format(DateTime.parse(log['date']).toLocal()),
                log['service_type'].toString().replaceAll('_', ' ').toUpperCase(),
                log['service_detail'] ?? '-',
                log['delivery_channel'] ?? '-',
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            "Generated by AgentBuddys",
            style: pw.TextStyle(
              fontSize: 12,
              color: PdfColors.grey,
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }
}
